# Generated by Django 4.2.2 on 2023-06-23 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
